(define list1 (list 1 3 (list 5 7) 9))
(display (car (cdr (car (cdr (cdr list1))))))
(newline)
(define list2 (list (list 7)))
(display (car (car list2)))
(newline)
(define list3 (list 1 (list 2 (list 3 (list 4 (list 5 (list 6 7)))))))
(display (car (cdr (car (cdr (car (cdr (car (cdr (car (cdr (car (cdr list3)))))))))))))
(newline)