(define (subsets s)
  (if (null? s)
      (list '())
      (let ((rest (subsets (cdr s)))
            (first (car s)))
        (append rest (map (lambda (x) (cons first x)) rest)))))

(display (subsets (list 1)))
(newline)
(display (subsets (list 1 2)))
(newline)
(display (subsets (list 1 2 3)))
(newline)
(display (subsets (list 1 2 3 4)))
(newline)