(define (tree-map function tree)
  (cond ((null? tree) '())
        ((pair? tree)
         (cons (tree-map function (car tree))
               (tree-map function (cdr tree))))
        (else (function tree))))

(define (accumulate op initial sequence)
  (if (null? sequence)
      initial
      (op (car sequence)
          (accumulate op initial (cdr sequence)))))

(define (accumulate-n op init seqs)
  (define (fetch-firsts seqs)
    (if (null? seqs)
        '()
        (cons (caar seqs) (fetch-firsts (cdr seqs)))))
  (define (fetch-rests seqs)
    (if (null? seqs)
        '()
        (cons (cdar seqs) (fetch-rests (cdr seqs)))))
  (if (null? (car seqs))
      '()
      (cons (accumulate op init (fetch-firsts seqs))
            (accumulate-n op init (fetch-rests seqs)))))

(define (flatmap proc seq)
  (accumulate append '() (map proc seq)))

; generate a list of integers between m and n(inclusively)
(define (enumerate-interval m n)
  (define (iter i)
    (if (> i n)
        '()
        (cons i (iter (+ i 1)))))
  (iter m)
)

(define (element-of-set? x set)
  (cond ((null? set) #f)
        ((equal? x (car set)) #t)
        (else (element-of-set? x (cdr set)))
  )
)

(define (adjoin-set x set)
  (if (element-of-set? x set)
      set
      (cons x set)
  )
)

(define (intersection-set set1 set2)
  (cond ((or (null? set1) (null? set2)) '())
        ((element-of-set? (car set1) set2)
         (cons (car set1) (intersection-set (cdr set1) set2)))
        (else (intersection-set (cdr set1) set2))
  )
)

(define (union-set set1 set2)
  (cond ((null? set1) set2)
        ((element-of-set? (car set1) set2) set2)
        (else (cons (car set1) (union-set (cdr set1) set2)))
  )
)